// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package forms.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import java.io.File;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import no.ntnu.ihb.fmi4j.importer.fmi2.CoSimulationSlave;
import no.ntnu.ihb.fmi4j.importer.fmi2.Fmu;
import no.ntnu.ihb.fmi4j.modeldescription.variables.TypedScalarVariable;
import no.ntnu.ihb.fmi4j.Fmi4jVariableUtils;
import org.json.JSONArray;
import org.json.JSONObject;
import com.mendix.core.Core;

public class JA_GetModelData extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private final java.lang.String ModelName;

	public JA_GetModelData(
		IContext context,
		java.lang.String _modelName
	)
	{
		super(context);
		this.ModelName = _modelName;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		
		// Instantiate fmu
		Fmu fmu = Fmu.from(new File("../userlib/" + this.ModelName)); //URLs are also supported
		CoSimulationSlave slave = fmu.asCoSimulationFmu().newInstance();
        slave.simpleSetup();
        
        // List to hold Mendix objects
        List<IMendixObject> paramList = new ArrayList<>();

        // Get variables from fmu
        var modelDescription = slave.getModelVariables();
        var it = modelDescription.iterator();
        
        // Iterate over model variables
        while (it.hasNext()) {
            TypedScalarVariable<?> element = it.next();
            
            // Create Mendix objects
            var param = Core.instantiate(getContext(), "Forms.FMUParameter");        
            Map<String, String> changes = new HashMap<>();
            changes.put("Name", element.getName());
            changes.put("Description", element.getDescription());
            changes.put("DataType", element.getType().getTypeName());
            
            Core.change(getContext(), param, changes);
            paramList.add(param);
        }
        
        slave.terminate(); 
        fmu.close();
                
        return paramList;
		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_GetModelData";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
