// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mendixsso.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class GetHttpRequestParameter extends CustomJavaAction<java.lang.String>
{
	/** @deprecated use HttpRequest.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __HttpRequest;
	private final system.proxies.HttpRequest HttpRequest;
	private final java.lang.String ParameterName;

	public GetHttpRequestParameter(
		IContext context,
		IMendixObject _httpRequest,
		java.lang.String _parameterName
	)
	{
		super(context);
		this.__HttpRequest = _httpRequest;
		this.HttpRequest = _httpRequest == null ? null : system.proxies.HttpRequest.initialize(getContext(), _httpRequest);
		this.ParameterName = _parameterName;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetHttpRequestParameter";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
